download.file("http://www.openintro.org/stat/data/bdims.RData", destfile = "bdims.RData")
load("bdims.RData")
mdims <- subset(bdims, bdims$sex==1)fdims <- subset(bdims, bdims$sex==0)
hist(mdims$hgt)
hist(fdims$hgt, plot = TRUE)
fhgtmean <- mean(fdims$hgt)
fhgtsd <- sd(fdims$hgt)
hist(fdims$hgt, probability = TRUE)
x <- 140:190
y <- dnorm(x=x, mean = fhgtmean, sd = fhgtsd)
lines(x, y, col = "blue")
qqnorm(fdims$hgt)
qqline(fdims$hgt)
sim_norm <- rnorm(n = length(fdims$hgt), mean = fhgtmean, sd = fhgtsd)
qqnorm(sim_norm)
qqline(sim_norm)
qqnormsim(fdims$hgt)
probShortThan6ft <- pnorm(q = 182, mean = fhgtmean, sd = fhgtsd)
probTallerThan6ft <- 1 - probShortThan6ft
sum(fdims$hgt > 182) / length(fdims$hgt)
probShortThan5ft <- pnorm(q = (182 / 6 * 5), mean = fhgtmean, sd = fhgtsd)
qqnorm(fdims$kne.di)
hist(fdims$kne.di)
